server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: client-searchService
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://59.110.160.154:3306/searchService?characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
#  jpa:
#    properties:
#      hibernate:
#        hbm2ddl:
#          auto: update