server:
  port: 8040
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: product-service-zuul
zuul:
  routes:
    api-category:
      path: /api-category/**
      serviceId: client-categoryService
    api-book:
      path: /api-search/**
      serviceId: client-searchService
    api-order:
      path: /api-order/**
      serviceId: client-orderService

