server:
  port: 8040
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: product-service-zuul

zuul:
  host:
    connect-timeout-millis: 1500000000 #HTTP连接超时要比Hystrix的大
    socket-timeout-millis: 60000   #socket超时

  routes:
    api-category:
      path: /api-category/**
      serviceId: client-categoryService
    api-book:
      path: /api-search/**
      serviceId: client-searchService
    api-order:
      path: /api-order/**
      serviceId: client-orderService
    api-inventory:
      path: /api-inventory/**
      serviceId: client-inventoryService
    api-type:
      path: /api-type/**
      serviceID: service-type
    api-user:
      path: /api-user/**
      serviceId: usr-service
    api-recommend:
      path: /api-recommend/**
      serviceId: service-recommend
