server:
  port: 8084
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: client-orderService
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://59.110.160.154:3306/orderService?characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
  activemq:
    broker-url: tcp://localhost:61616
    in-memory: true
    pool:
      enabled: false
